import random
#This will hold a randomly generated number between 1 and 10
secretNumber = random.randint(1, 10)
print(secretNumber)
#I initialized 'guess' with 0 since it's outside of the range specified by secretNumber
guess = 0
#The loop will iterate as long as 'guess' isn't equal to the number generated by 'secretNumber'
while guess != secretNumber:
    guess = int(input("Pick a number between 1 and 10"))
    #if the user guesses correctly, a congratulatory message will be displayed.
    if guess == secretNumber:
        print(("You guessed correctly"))
        #Otherwise, this message will be displayed
    else:
        print("Incorrect, try again.")
